import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerate with: npm run gen-api-docs warehouse-planning
import apiSidebar from './docs/api-reference/rest/sidebar';

/**
 * Top-level categories follow the shared warehouse-systems documentation
 * layout: Overview, Domain-Driven Design, API Reference, Ecosystem and
 * Architecture Decision Records. The ADR files live in docs/adr/ and are served
 * by the second docs plugin instance (id: 'adr'), hence the plain links.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/context'},
      items: [
        'overview/aggregates',
        'overview/capacity-composition',
        'overview/runtime',
      ],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/ubiquitous-language'},
      items: ['ddd/use-cases'],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api-reference/overview'},
      items: [...apiSidebar, 'api-reference/events'],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {type: 'doc', id: 'ecosystem/upstream-contracts'},
      items: [],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      items: [
        {
          type: 'link',
          label: '0001 Bounded context',
          href: '/docs/adr/0001-warehouse-planning-bounded-context',
        },
        {
          type: 'link',
          label: '0002 Station capacity composition',
          href: '/docs/adr/0002-station-capacity-composition',
        },
        {
          type: 'link',
          label: '0003 Window coverage semantics',
          href: '/docs/adr/0003-window-coverage-semantics',
        },
      ],
    },
  ],
};

export default sidebars;
