import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// ADR files live in docs/adr/ (other repos link to those paths) and are
// served in place by the second docs plugin instance (id: 'adr').
const sidebars: SidebarsConfig = {
  adrSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
